global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'pos-alerts@yourcompany.com'
  smtp_auth_username: 'pos-alerts@yourcompany.com'
  smtp_auth_password: 'your-email-password'

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route tree for alert routing
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
    
    # Warning alerts - standard notification
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 30m
    
    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      repeat_interval: 24h
    
    # Database specific alerts
    - match_re:
        alertname: '^(MongoDB|Redis).*'
      receiver: 'database-alerts'
    
    # Business logic alerts
    - match_re:
        alertname: '^(UnusualSales|NoSales|CashDrawer|HighRefund).*'
      receiver: 'business-alerts'

# Inhibition rules to suppress redundant alerts
inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
  
  # Suppress individual service alerts when the entire node is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '^(High|Low|Container).*'
    equal: ['instance']

# Receivers define how to send notifications
receivers:
  # Default receiver
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@yourcompany.com'
        subject: '[POS Alert] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@yourcompany.com,manager@yourcompany.com'
        subject: '[CRITICAL] POS System Alert: {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          This requires immediate attention!
          {{ end }}
    
    # Slack notification for critical alerts
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#pos-alerts'
        title: '🚨 Critical POS System Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: 'danger'
    
    # SMS notification (using webhook)
    webhook_configs:
      - url: 'http://your-sms-service/webhook'
        send_resolved: true

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'admin@yourcompany.com'
        subject: '[WARNING] POS System: {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#pos-alerts'
        title: '⚠️ POS System Warning'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Instance:* {{ .Labels.instance }}
          {{ end }}
        color: 'warning'

  # Info alerts - daily digest
  - name: 'info-alerts'
    email_configs:
      - to: 'manager@yourcompany.com'
        subject: '[INFO] POS System Daily Report'
        body: |
          📊 Daily POS System Report
          
          {{ range .Alerts }}
          • {{ .Annotations.summary }}
          {{ end }}

  # Database alerts
  - name: 'database-alerts'
    email_configs:
      - to: 'dba@yourcompany.com,admin@yourcompany.com'
        subject: '[DATABASE] POS System: {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.job }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # Business alerts
  - name: 'business-alerts'
    email_configs:
      - to: 'manager@yourcompany.com,finance@yourcompany.com'
        subject: '[BUSINESS] POS Alert: {{ .GroupLabels.alertname }}'
        body: |
          💼 BUSINESS ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Please review business operations.
          {{ end }}
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#pos-business'
        title: '💼 POS Business Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
        color: 'good'