groups:
  - name: pos-system-alerts
    rules:
      # Service Availability Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.instance }}"

      # Database Alerts
      - alert: MongoDBDown
        expr: mongodb_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MongoDB is down"
          description: "MongoDB instance {{ $labels.instance }} is down"

      - alert: MongoDBHighConnections
        expr: mongodb_connections{state="current"} / mongodb_connections{state="available"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MongoDB high connection usage"
          description: "MongoDB connection usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: MongoDBSlowQueries
        expr: rate(mongodb_op_counters_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MongoDB slow queries detected"
          description: "MongoDB is experiencing {{ $value }} operations per second on {{ $labels.instance }}"

      # Redis Alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} is down"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      # System Resource Alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }} mount {{ $labels.mountpoint }}"

      # Application-Specific Alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.instance }}"

      - alert: LowInventoryStock
        expr: pos_inventory_stock_level < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Low inventory stock"
          description: "Product {{ $labels.product_name }} has only {{ $value }} items left in stock"

      - alert: FailedTransactions
        expr: rate(pos_transactions_total{status="failed"}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High failed transaction rate"
          description: "Failed transaction rate is {{ $value }} per second"

      # Container Alerts
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value }}%"

      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value }}%"

      - alert: ContainerRestarting
        expr: rate(container_last_seen[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container restarting"
          description: "Container {{ $labels.name }} is restarting frequently"

  - name: pos-business-alerts
    rules:
      # Business Logic Alerts
      - alert: UnusualSalesVolume
        expr: rate(pos_sales_total[1h]) > (avg_over_time(rate(pos_sales_total[1h])[7d]) * 2)
        for: 15m
        labels:
          severity: info
        annotations:
          summary: "Unusual sales volume detected"
          description: "Current sales rate is {{ $value }} which is significantly higher than average"

      - alert: NoSalesActivity
        expr: rate(pos_sales_total[2h]) == 0
        for: 2h
        labels:
          severity: warning
        annotations:
          summary: "No sales activity detected"
          description: "No sales have been recorded in the last 2 hours during business hours"

      - alert: CashDrawerDiscrepancy
        expr: abs(pos_cash_drawer_expected - pos_cash_drawer_actual) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Cash drawer discrepancy detected"
          description: "Cash drawer has a discrepancy of ${{ $value }}"

      - alert: HighRefundRate
        expr: rate(pos_refunds_total[1h]) / rate(pos_sales_total[1h]) > 0.1
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "High refund rate detected"
          description: "Refund rate is {{ $value | humanizePercentage }} which is unusually high"